name : Amra Codeigniter 3 Auto Pull Request

on: 
  push:
    branches: [development]
    
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: diillson/auto-pull-request@latest
        with:
          source_branch: "development"
          destination_branch: "master"
